spring:
  application:
    name: shop-service

  datasource:
    url: jdbc:postgresql://${DB_HOST_URL}/${DB_NAME}?useSSL=false
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

secret:
  key: ${SECRET_KEY}

server:
  servlet:
    context-path: /shops
  port: 9050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka