spring:
  application:
  name: customer-service

  datasource:
    url: jdbc:postgresql://${DB_HOST_URL}/${DB_NAME}?useSSL=false
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

secret:
  key: ${SECRET_KEY}

server:
  servlet:
    context-path: /customers
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka