spring:
  application:
  name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST_URL}/${DB_NAME}?useSSL=false
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9060

secret:
  key: ${SECRET_KEY}