spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_SERVER_URL}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main

server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/